/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function ContactMe(props) {
  const { nodes, materials } = useGLTF('/models/stylized+person+3d+model.glb')
  return (
    <group {...props} dispose={null} scale={2} position={[0, 0, 0]} rotation={[0, -Math.PI/2, 0]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['tripo_node_3858f092-59f3-4c4f-b0a4-ea7f3d23826f'].geometry}
        material={materials['tripo_mat_3858f092-59f3-4c4f-b0a4-ea7f3d23826f']}
      />
    </group>
  )
}

useGLTF.preload('/models/stylized+person+3d+model.glb')
