/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function ProTable(props) {
  const { nodes, materials } = useGLTF('/models/space+game+scene+3d+model.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['tripo_node_515a683c-0225-4d71-be3c-51df8d355d6a'].geometry}
        material={materials['tripo_mat_515a683c-0225-4d71-be3c-51df8d355d6a']}
      />
    </group>
  )
}

useGLTF.preload('/space+game+scene+3d+model.glb')
