/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Ster(props) {
  const { nodes, materials } = useGLTF('/models/star trophy 3d model.glb')
  return (
    <group {...props} dispose={null} scale={3} position={[0, 0, 0]} rotation={[0, Math.PI/2, 0]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['tripo_node_254ee135-f849-48a6-8ce8-d4b1391ca39a'].geometry}
        material={materials['tripo_material_254ee135-f849-48a6-8ce8-d4b1391ca39a']}
      />
    </group>
  )
}

useGLTF.preload('/star trophy 3d model.glb')
