/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
"use client"
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Vr(props) {
  const { nodes, materials } = useGLTF('/models/vr headset 3d model (1).glb')
  return (
    <group {...props} dispose={null} scale={6} position={[0, -1.5, 0]} rotation={[-0.4, -1.6, 0]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['tripo_node_d0d13ad3-4ee3-43cb-ad0f-10f426005351'].geometry}
        material={materials['tripo_material_d0d13ad3-4ee3-43cb-ad0f-10f426005351']}
      />
    </group>
  )
}

useGLTF.preload('/vr headset 3d model (1).glb')
